finalproject/elibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexview, name='index-view'),
    path('users/', include('users.urls')),
    path('student/', include('student.urls')),
    path('librarian/', include('librarian.urls')),
]

finalproject/users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    path('', loginview, name='login-view'),
    path('login/', validationview, name='user-validation-view'),
    path('forgot-password/', forgotpasswordview, name='forgot-password-view'),
    path('set-password/', setpasswordview, name='set-password-view'),
    path('set-password/update/', updatepasswordview, name='update-password-view'),
    path('view-profile/', viewprofileview, name='view-profile-view'),
    path('search/', searchresultview, name='search-result-view'),
    path('forgot-password/send-otp/', sendotpview, name="send-otp-view"),
    path('forgot-password/resend-otp/', resendotpview, name="resend-otp-view"),
    path('forgot-password/verify-otp/', verifyotpview, name="verify-otp-view"),
    path('logout', logoutview, name="logout-view"),
]

finalproject/templates/base.html
{% load static %}
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/css/base.css' %}"> {% block head-part %} {% endblock %}
</head>

<body>
    <div class="container-fluid">
        <div class="row container-color sticky-top ">
            <div class="col-12">
                <div class="container-fluid">
                    <div class="row ">
                        <div class="col-1 py-3 pl-5 pr-5">
                            <svg xmlns="http://www.w3.org/2000/svg" width="70" height="70" fill="white" class="bi bi-book bi-fluid" viewBox="0 0 16 16">
                                <path
                                    d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z" />
                            </svg>
                        </div>
                        <div class="col-5 py-4 px-4 ">
                            <h2 class="h3color" style="font-size:2.45vw;">Prof. B. Sarveswara Rao, Library </h2>
                        </div>
                        <div class="col ">
                            {% block header-other-half %} {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" {% block bg-part %} {% endblock %}>
            <div class="col">
                <div class="container-fluid ">
                    <div class="scrol" style='height: 610px; overflow-y:scroll'>
                        {% block body-part %} {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row container-color fixed-bottom">
            <div class="col-12">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-6 col-align mt-2">
                            <p class='p-color'>Land Line : 91-891-2739507 , Ext (316) </p>
                        </div>
                        <div class="col-6 col-align mt-2">
                            <p class='p-color'>Mobile : 08885043442</p>
                        </div>
                        <div class="col-6 col-align">
                            <p class='p-color'>Fax : 0891 – 2739605</p>
                        </div>
                        <div class="col-6 col-align">
                            <p class='p-color'>Email : librarian@gvpce.ac.in</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>


</body>

</html>

finalproject/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head-part %}
<link rel="stylesheet" href="{% static 'users/css/index.css' %}">
{% endblock %}

{% block header-other-half %}
<div class="container">
    <div class="row">
        <div class="col mt-4 pt-1  mr-4 pr-5 text-align ">
            <a href="{% url 'users:login-view' %}">
                <text class="logincolor" style="font-size:1.8vw;">Login</text>
            </a>
        </div>
    </div>
</div>
{% endblock %}

{% block bg-part %}
style="background:rgba(133, 210, 242, 0.4);"
{% endblock %}

{% block body-part %}
<div class="container pl-5">
    <div class="row mt-4 pl-4">
        <div id="carouselExampleIndicators" class="carousel slide pt-2" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block rounded" src="{% static 'users/images/lib1.jpg' %}" alt="First slide" width=1025
                        height=500>
                </div>
                <div class="carousel-item">
                    <img class="d-block rounded" src="{% static 'users/images/lib2.jpg' %}" alt="Second slide"
                        width=1025 height=500>
                </div>
                <div class="carousel-item">
                    <img class="d-block rounded" src="{% static 'users/images/lib3.jpg' %}" alt="Third slide" width=1025
                        height=500>
                </div>
                <div class="carousel-item">
                    <img class="d-block rounded" src="{% static 'users/images/lib4.jpg' %}" alt="Third slide" width=1025
                        height=500>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<div class="container my-5">
    <div class="row px-5">
        <text class="lib_txt pb-1">Library Collection</text>
        <table class="table table_control">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">S No</th>
                    <th scope="col">BRANCH</th>
                    <th scope="col">TITLES</th>
                    <th scope="col">VOLUMES</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>CHEMICAL ENGINEERING</td>
                    <td>1483</td>
                    <td>3463</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>CIVIL ENGINEERING</td>
                    <td>1878</td>
                    <td>8709</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>COMPUTER SCIENCE ENGINEERING</td>
                    <td>3028</td>
                    <td>11693</td>
                </tr>
                <tr>
                    <th scope="row">4</th>
                    <td>INFORMATION TECHNOLOGY</td>
                    <td>2041</td>
                    <td>6671</td>
                </tr>
                <tr>
                    <th scope="row">5</th>
                    <td> MECHANICAL ENGINEERING</td>
                    <td>2810</td>
                    <td>11101</td>
                </tr>
                <tr>
                    <th scope="row">6</th>
                    <td> ELECTRICAL & ELECTRONICS ENGINEERING</td>
                    <td> 2204</td>
                    <td>7078</td>
                </tr>

                <tr>
                    <th scope="row">7</th>
                    <td>ELECTRONICS AND COMMUNICATIONS ENGINEERING</td>
                    <td>2724</td>
                    <td>12822</td>
                </tr>
            </tbody>
        </table>
    </div>

</div>


{% endblock %}