finalproject/elibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexview, name='index-view'),
    path('users/', include('users.urls')),
    path('student/', include('student.urls')),
    path('librarian/', include('librarian.urls')),
]

finalproject/librarian/urls.py
from django.urls import path, include

from .views import *

app_name = 'librarian'

urlpatterns = [
    path('home/', homepageview, name='home-page-view'),
    path('home/student-profile/', studentprofileview,
         name='student-profile-view'),
    path('home/issue-book/', issuebookview, name='issue-book-view'),
    path('home/submit-book/', submitbookview, name='submit-book-view'),
    path('send-notifications/', sendnotificationsview,
         name='send-notifications-view'),
]

finalproject/student/urls.py
from django.urls import path, include

from .views import *

app_name = 'student'

urlpatterns = [
    path('home/', homepageview, name='home-page-view'),
    path('home/pay/<int:bookid>/', paymentview, name='payment-view'),
    path('home/pay/<int:bookid>/success/',
         paymentsuccessview, name='payment-success-view'),
    path('home/pay/<int:bookid>/failure/',
         paymentfailureview, name='payment-failure-view'),
]

finalproject/users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    path('', loginview, name='login-view'),
    path('login/', validationview, name='user-validation-view'),
    path('forgot-password/', forgotpasswordview, name='forgot-password-view'),
    path('set-password/', setpasswordview, name='set-password-view'),
    path('set-password/update/', updatepasswordview, name='update-password-view'),
    path('view-profile/', viewprofileview, name='view-profile-view'),
    path('search/', searchresultview, name='search-result-view'),
    path('forgot-password/send-otp/', sendotpview, name="send-otp-view"),
    path('forgot-password/resend-otp/', resendotpview, name="resend-otp-view"),
    path('forgot-password/verify-otp/', verifyotpview, name="verify-otp-view"),
    path('logout', logoutview, name="logout-view"),
]

finalproject/users/forms.py
from django import forms

# django forms


class loginform(forms.Form):
    userid = forms.CharField(max_length=10, label='Your User ID', required=True, widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'autofocus': 'True',
        'size': '24',
    }))
    psw = forms.CharField(max_length=15, label='Your Password', required=True, widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'size': '24',
    }))


class sendotpform(forms.Form):
    userid = forms.CharField(max_length=10, label='Your User ID', required=True, widget=forms.TextInput(attrs={
        'placeholder': 'User ID',
        'autofocus': 'True',
        'class': 'input_align',
        'id': 'userid',
        'size': '40',

    }))


class verifyotpform(forms.Form):
    otp = forms.CharField(max_length=6, label='Your OTP', required=True, widget=forms.TextInput(attrs={
        'placeholder': 'Enter OTP',
        'autofocus': 'True',
        'class': 'input_align',
        'size': '40',
        'id': 'otp',
    }))


class setpasswordform(forms.Form):
    psw1 = forms.CharField(max_length=15, label='Enter New Password', required=True, widget=forms.PasswordInput(attrs={
        'autofocus': 'True',
        'id': 'InputPasswordNew',
    }))
    psw2 = forms.CharField(max_length=15, label='Retype New Password', required=True, widget=forms.PasswordInput(attrs={
        'id': 'RetypePasswordNew',
    }))


class searchboxform(forms.Form):
    searchbox = forms.CharField(max_length=100, label='Search Here', widget=forms.TextInput(attrs={
        'placeholder': '     Search Book',
        'id': 'book',
        'class': 'form-bg',
    }))

finalproject/users/views.py
from .sms import *
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse

from itertools import chain

from .forms import *
from users.models import *
from student.models import *
from librarian.models import *
# Create your views here.

def loginview(request, *args, **kwargs):
    form = loginform()
    try:
        errors = request.session['auth_errors']
        del request.session['auth_errors']
    except:
        errors = ""
    try:
        logoutmsg = request.session['logout_msg']
    except:
        logoutmsg = ''
    if 'logout_msg' in request.session:
        del request.session['logout_msg']
    if 'curr_user_id' in request.session:
        del request.session['curr_user_id']
    if 'issue_book_error' in request.session:
        del request.session['issue_book_error']
    if 'submit_book_error' in request.session:
        del request.session['submit_book_error']
    if 'errors' in request.session:
        del request.session['errors']
    if 'otp_sent' in request.session:
        del request.session['otp_sent']
    if 'otp_session_data' in request.session:
        del request.session['otp_session_data']
    if 'otp_status' in request.session:
        del request.session['otp_status']
    if 'resend_otp' in request.session:
        del request.session['resend_otp']
    return render(request, 'users/login.html', {
        'form': form,
        'errors': errors,
        'logout_msg': logoutmsg,
    })

def validationview(request, *args, **kwargs):
    if request.method == 'POST':
        form = loginform(request.POST)
        if form.is_valid():
            try:
                user = Library_Users.objects.get(
                    userid=form.cleaned_data['userid'])
            except:
                request.session['curr_user_id'] = 'anonymous'
                request.session['auth_errors'] = 'Invalid Username/Password'
                return HttpResponseRedirect(reverse('users:login-view'))
            if (user.password == form.cleaned_data['psw']):
                request.session['curr_user_id'] = form.cleaned_data['userid']
                # print(request.session['curr_user_id'])
                if (user.isLibrarian):
                    return HttpResponseRedirect(reverse('librarian:home-page-view'))
                else:
                    return HttpResponseRedirect(reverse('student:home-page-view'))
            else:
                request.session['curr_user_id'] = 'anonymous'
                request.session['auth_errors'] = 'Invalid Username/Password'
    return HttpResponseRedirect(reverse('users:login-view'))


def sendotpview(request, *args, **kwargs):
    # valid incoming user from the request
    # print(request.session['curr_user_id'])
    try:
        user = Library_Users.objects.get(
            userid=request.session['curr_user_id'])
        if user.isLibrarian:
            active_user = Librarian.objects.get(libid=user)
        else:
            active_user = Students.objects.get(studid=user)
        request.session['otp_session_data'] = send_otp(active_user.phone)
        request.session['otp_sent'] = True
    except:
        request.session['curr_user_id'] = 'anonymous'
        request.session['errors'] = 'Invalid User ID'
        request.session['otp_sent'] = False
    
    return HttpResponseRedirect(reverse('users:forgot-password-view'))

def verifyotpview(request, *args, **kwargs):
    request.session['otp_status'] = ''
    if request.method == 'POST':
        verification_form = verifyotpform(request.POST)
        if verification_form.is_valid():
            response_data = otp_verification(request, verification_form.cleaned_data['otp'])
            if response_data['Message'] == 'Success':
                request.session['otp_status'] = 'Success'
                return HttpResponseRedirect(reverse('users:set-password-view'))
            else:
                request.session['otp_status'] = 'Invalid OTP!'
                otpform = sendotpform()
                errors = ''
                verify_otpform = verifyotpform()
                return  render(request, 'users/forgotpassword.html', {
                    'sent_otp': request.session['otp_sent'],
                    'otpform': otpform,
                    'verify_otpform': verify_otpform,
                    'errors': errors,
                    'resend_otp': False,
                    'otp_status': request.session['otp_status'],
                })
        else:
            request.session['otp_status'] = 'Invalid OTP!'
            return HttpResponseRedirect(reverse('users:forgot-password-view'))

def forgotpasswordview(request, *args, **kwargs):
    if request.method == 'POST':
        if request.session['otp_sent']:
            otpform = sendotpform()
            errors = ''
            return render(request, 'users/forgotpassword.html', {
                'sent_otp': request.session['otp_sent'],
                'otpform': otpform,
                'errors': errors,
            })
        else:
            print(request.POST)
            otpform = sendotpform(request.POST)
            if otpform.is_valid():
                request.session['curr_user_id'] = otpform.cleaned_data['userid']
                print(request.session['curr_user_id'])
            else:
                request.session['curr_user_id'] = 'xxx'
            return HttpResponseRedirect(reverse('users:send-otp-view'))
    else:
        try:
            if request.session['otp_sent']:
                otpform = sendotpform()
                errors = ''
                verify_otpform = verifyotpform()
                try:
                    if request.session['resend_otp']:
                        resend_otp = True
                        request.session['resend_otp'] = False
                except:
                    request.session['resend_otp'] = False
                    resend_otp = False

                return render(request, 'users/forgotpassword.html', {
                    'sent_otp': request.session['otp_sent'],
                    'otpform': otpform,
                    'verify_otpform': verify_otpform,
                    'errors': errors,
                    'resend_otp': resend_otp,
                })
            else:
                otpform = sendotpform()
                errors = request.session['errors']
                del request.session['errors']
        except:
            request.session['otp_sent'] = False
            otpform = sendotpform()
            errors = ''
    return render(request, 'users/forgotpassword.html', {
        'sent_otp': request.session['otp_sent'],
        'otpform': otpform,
        'errors': errors,
    })

def resendotpview(request, *args, **kwargs):
    request.session['resend_otp'] = True
    return HttpResponseRedirect(reverse('users:send-otp-view'))

def setpasswordview(request, *args, **kwargs):
    pswform = setpasswordform()
    try:
        errors = request.session['password_errors']
        del request.session['password_errors']
    except:
        errors = ""
    return render(request, 'users/setpassword.html', {
        'pswform': pswform,
        'pswerrors': errors,
    })

def updatepasswordview(request, *args, **kwargs):
    if request.method == 'POST':
        pswform = setpasswordform(request.POST)
        if pswform.is_valid():
            if pswform.cleaned_data['psw1'] == pswform.cleaned_data['psw2']:
                user = Library_Users.objects.get(
                    userid=request.session['curr_user_id'])
                user.password = pswform.cleaned_data['psw1']
                user.save()
                if (user.isLibrarian):
                    return HttpResponseRedirect(reverse('librarian:home-page-view'))
                else:
                    return HttpResponseRedirect(reverse('student:home-page-view'))
            else:
                request.session['password_errors'] = 'New Password not matching with Retyped Password!!'
                return HttpResponseRedirect(reverse('users:set-password-view'))
    else:
        return HttpResponseRedirect(reverse('users:set-password-view'))

def logoutview(request, *args, **kwargs):
    request.session['logout_msg'] =  'You have been logged out successfully!!'
    return HttpResponseRedirect(reverse('users:login-view'))

def viewprofileview(request, *args, **kwargs):
    user = Library_Users.objects.get(userid=request.session['curr_user_id'])
    profileimgurl = f'users/images/{user.userid}.jpg'
    if user.isLibrarian:
        librarian = Librarian.objects.get(libid=user)
        return render(request, 'users/viewprofile.html', {
            'username': user.userid,
            'librarian': librarian,
            'isLibrarian': user.isLibrarian,
            'profileImage': profileimgurl,
        })
    else:
        student = Students.objects.get(studid=user)
        return render(request, 'users/viewprofile.html', {
            'username': user.userid,
            'student': student,
            'isLibrarian': user.isLibrarian,
            'profileImage': profileimgurl,
        })


def searchresultview(request, *args, **kwargs):
    username = request.session['curr_user_id']
    user = Library_Users.objects.get(userid=username)
    if request.method == 'GET':
        searchform = searchboxform(request.GET)
        if searchform.is_valid():
            keyword = searchform.cleaned_data['searchbox']
            keywords = keyword.split()
            if len(keywords) < 2:
                if len(keywords) == 1:
                    booklist = Books.objects.filter(
                        bookname__icontains=keywords[0])
                else:
                    booklist = {}
            else:
                booklist = list()
                for word in keywords:
                    booklist.append(Books.objects.filter(
                        bookname__icontains=word))
                booklist = list(chain(*booklist))
            return render(request, 'users/searchresult.html', {

finalproject/users/templates/users/forgotpassword.html
{% extends 'base.html' %}
{% load static %}

{% block head-part %}
<link rel="stylesheet" href="{% static 'users/css/forgotpassword.css' %}">
{% endblock %}

{% block header-other-half %}
<div class="container">
    <div class="row">
        <div class="col mt-4 pt-1  mr-4 pr-5 text-align ">
            <a href="{% url 'users:login-view' %}">
                <text class="logincolor" style="font-size:1.8vw;">Login</text>
            </a>
        </div>
    </div>
</div>
{% endblock %}

{% block body-part %}
<div class="container pb-5">
    {% if not sent_otp %}
    <div class="row ml-5 my-5 pt-2 pl-5">
        <div class="col-12 pl-5 ml-5">
            <div style="text-align:center" class="ml-5 pl-5">
                <div class="card card-bg" style="width: 35rem; height:12rem">
                    <div class="card-header card_head_color pt-2">
                        <text class="active_txt">Enter UserID</text>
                    </div>
                    <div class=" card-body py-3 mt-3 pb-4">
                        <form action="{% url 'users:forgot-password-view' %}" method="POST">
                            {% csrf_token %}
                            <div class="pb-3">
                                {{ otpform.userid }}
                            </div>
                            <input id="send_otp" class="btn btn-sm btn-primary " value="Send OTP" type="submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4 pl-4">
        <div class="col-12">
            <div style="text-align:center" class="">
                {% if errors %}
                <div class="alert alert-danger alert-dismissible fade show" style="width:fit-content; margin: 0 auto;" role="alert">
                    <strong><span>{{ errors }}</span></strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% else %}
    <div class="row ml-5 my-5 pt-2 pl-5">
        <div class="col-12 pl-5 ml-5">
            <div style="text-align:center" class="ml-5 pl-5">
                <div class="card card-bg" style="width: 35rem; height:17rem">
                    <div class="card-header card_head_color pt-2">
                        <text class="active_txt">Enter OTP and Verify</text>
                    </div>
                    <div class=" card-body py-3 mt-3">
                        <form action="{% url 'users:verify-otp-view' %}" method="POST">
                            {% csrf_token %}
                            <div class="pb-3">
                                {{ verify_otpform.otp }}
                            </div>
                            <input id="verify" class="btn btn-sm btn-primary " value="Verify OTP" type="submit">
                        </form>
                        <div class="resend-otp" id="resend-otp-button" style="width: fit-content; display:none;">
                            <form action="{% url 'users:resend-otp-view' %}" method="POST" style="padding-top: 20px;">
                                {% csrf_token %}
                                <input id="Resend_OTP" class="btn btn-sm btn-danger " value="Resend OTP" type="submit">
                            </form>
                        </div>
                        <div>
                            <strong style="padding-top: 10px; margin-top: 10px;">
                                <span class="timer_msg"></span>
                            </strong>
                        </div>
                        <script>
                            document.addEventListener('DOMContentLoaded', () => {
                                var seconds = 30;
                                var foo;
                                function fadeInButton() {
                                    document.querySelector(".timer_msg").innerHTML = "";
                                    document.getElementById("resend-otp-button").style.display = "initial";
                                }
                                function updateSecs() {
                                    document.querySelector(".timer_msg").innerHTML = "Resend OTP option appears in " + seconds + "s.";
                                    seconds--;
                                    if (seconds == -1) {
                                        clearInterval(foo);
                                        fadeInButton();
                                    }
                                }
                                function countdownTimer() {
                                    foo = setInterval(function () {
                                        updateSecs()
                                    }, 1000);
                                }
                                countdownTimer();
                            });
                        
                        </script>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12">
            <div style="text-align:center">
                {% if resend_otp %}
                    {% if not otp_status %}
                    <div class="alert alert-success alert-dismissible fade show" style="width:fit-content; margin: 0 auto;" role="alert">
                        <strong><span>OTP re-sent successfully on your registered mobile number!!</span></strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                {% else %}
                    {% if not otp_status %}
                    <div class="alert alert-success alert-dismissible fade show" style="width:fit-content; margin: 0 auto;" role="alert">
                        <strong><span>OTP sent successfully on your registered mobile number.</span></strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                {% endif %}
                {% if otp_status %}
                <div class="alert alert-danger alert-dismissible fade show" style="width:fit-content; margin: 0 auto;" role="alert">
                    <strong><span>{{ otp_status }}</span></strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

finalproject/users/templates/users/searchresult.html
{% extends 'base.html' %}
{% load static %}

{% block head-part %}
<link rel="stylesheet" href="{% static 'users/css/searchresult.css' %}">
{% endblock %}

{% block header-other-half %}
<div class="container">
  <div class="row m-4 p-2 ">
    <div class="col text-align ml-5">
      <a href='{% url "users:view-profile-view" %}'>
        <text class="rollno-color ">{{ username }}</text>
      </a>
    </div>

    <div class="col lout-text-align ">
      <a href="{% url 'users:logout-view' %}">
        <text class="logoutcolor">Logout</text>
      </a>
    </div>
  </div>
</div>
{% endblock %}

{% block body-part %}

<div class="container-fluid">
  <div class="row m-3 px-3 pt-2">
    <div class="col pl-5">
      <form action="{% url 'users:search-result-view' %}" method="GET">
        {{ searchform.searchbox }}
        <!-- <input type="search" class="form-bg" id="profile" placeholder="     Search Book"> -->
        <input type="submit" class="search-button" value="">
      </form>
    </div>
  </div>

  <div class="row pt-1 px-5">
    <div class="col-12 px-5">
      <div style="max-height: 400px;overflow-y: scroll; overflow-x: hidden;">
        {% if booklist %}
        <table class="table table-color">
          <thead>
            <tr>
              <th scope="col">Book ID</th>
              <th scope="col">Book Name</th>
              <th scope="col">Author Name</th>
              <th scope="col">Edition</th>
              <th scope="col">Copies Available</th>
              <th scope="col">Shelf</th>
              <th scope="col">Dept</th>
            </tr>
          </thead>
          <tbody>
            {% for tuple in booklist %}
            <tr>
              <td scope="col">{{ tuple.bookid }}</td>
              <td scope="col">{{ tuple.bookname }}</td>
              <td scope="col">{{ tuple.author }}</td>
              <td scope="col">{{ tuple.edition }}</td>
              <td scope="col">{{ tuple.copies }}</td>
              <td scope="col">{{ tuple.shelf }}</td>
              <td scope="col">{{ tuple.dept|upper }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <div class="alert alert-warning alert-dismissible fade show" style="width:fit-content; margin: 0 auto;" role="alert">
          <strong>Sorry, No books found for your query search.</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %}
      </div>
    </div>
  </div>

</div>

<div class="container returnbtn ">
  <div class="row mt-4  " style="text-align:center">
    <div class="col">
      {% if user.isLibrarian %}
      <a href="{% url 'librarian:home-page-view' %}"><button type="submit">Return to home page</button></a>
      {% else %}
      <a href="{% url 'student:home-page-view' %}"><button type="submit">Return to home page</button></a>
      {% endif %}
    </div>
  </div>
</div>


{% endblock %}

finalproject/users/templates/users/viewprofile.html
{% extends 'base.html' %} {% load static %} {% block head-part %}
<link rel="stylesheet" href="{% static 'users/css/viewprofile.css' %}"> {% endblock %} {% block bg-part %} style="background:transparent url('{% static 'users/images/hologram.png' %}') no-repeat fixed center center / 40% 70%" {% endblock %} {% block header-other-half %}
<div class="container">
    <div class="row m-4 p-2 ">
        <div class="col text-align ml-5">
            <a href='{% url "users:view-profile-view" %}'>
                <text class="rollno-color ">{{ username }}</text>
            </a>
        </div>

        <div class="col lout-text-align ">
            <a href="{% url 'users:logout-view' %}">
                <text class="logoutcolor">Logout</text>
            </a>
        </div>
    </div>
</div>
{% endblock %} {% block body-part %}

<script>
    function callfun(obj) {
        var noimg = "{% static 'users/images/alt.png' %}";
        obj.src = noimg;
    }
</script>

{% if not isLibrarian %}

<div class="container mt-4">
    <div style="text-align:center">
        <text class="profile_txt">PROFILE</text>
    </div>
    <div class="row box-color m-4 p-4">
        <div class="col-4 pt-4 mt-2 pl-5">
            <div class="profile-img">
                <img src="{% static profileImage %}" alt="profile-img" onerror="callfun(this);" width=200 height=200 />
            </div>
        </div>
        <div class="col-8">
            <table>
                <tbody>
                    <tr>
                        <td class="txt-format">Name</td>
                        <td class="txt-format pl-3">{{ student.title }}. {{ student.name }}</td>
                    </tr>
                    <tr>
                        <td class="txt-format">Roll Number</td>
                        <td class="txt-format pl-3">{{ student.studid }}</td>
                    </tr>
                    <tr>
                        <td class="txt-format">Email ID</td>
                        <td class="txt-format pl-3">{{ student.email }}</td>
                    </tr>
                    <tr>
                        <td class="txt-format">Phone Number</td>
                        <td class="txt-format pl-3">(+91) {{ student.phone }}</td>
                    </tr>
                    <tr>
                        <td class="txt-format">Batch Number</td>
                        <td class="txt-format pl-3">{{ student.academicyear|truncatechars:5 }}Graduation</td>
                    </tr>
                    <tr>
                        <td class="txt-format">Section</td>
                        <td class="txt-format pl-3">{{ student.section }}</td>
                    </tr>
                    <tr>
                        <td class="txt-format">Amount Paid till now</td>
                        <td class="txt-format pl-3">Rs. {{ student.amountpaid }}</td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="container returnbtn lout-text-align  mr-5 pr-5">
    <div class="row mt-5 pr-5 mr-5">
        <div class="col mr-5 pr-5">
            <a href="{% url 'student:home-page-view' %}"><button type="submit">Return to home page</button></a>
        </div>
    </div>
</div>


{% else %}

<div class="container mt-4">
    <div style="text-align:center" class="mt-3">
        <text class="profile_txt">PROFILE</text>
    </div>
    <div class="row box-color m-4 p-4">
        <div class="col-4 pt-3 mt-1 pb-3 px-5">
            <div class="profile-img pl-5">
                <img src="{% static profileImage %}" alt="profile-img" onerror="callfun(this);" width=180 height=200>
            </div>
        </div>
        <div class="col-8 pl-5  pt-4">
            <table>
                <tbody>
                    <tr>
                        <td class="txt-format">Name</td>
                        <td class="txt-format pl-3">{{ librarian.title }}. {{ librarian.name }}</td>
                    </tr>
                    <tr>
                        <td class="txt-format">User ID</td>
                        <td class="txt-format pl-3">{{ librarian.libid }}</td>
                    </tr>
                    <tr>
                        <td class="txt-format">Email ID</td>
                        <td class="txt-format pl-3">{{ librarian.email }}</td>
                    </tr>
                    <tr>
                        <td class="txt-format">Number Of Books Issued</td>
                        <td class="txt-format pl-3">{{ librarian.issuedcount }}</td>
                    </tr>
                    <tr>
                        <td class="txt-format">Number Of Books Retrieved</td>
                        <td class="txt-format pl-3">{{ librarian.retrievedcount }}</td>
                    </tr>
                    <tr>
                        <td class="txt-format">Total number of Actions</td>
                        <td class="txt-format pl-3">{{ librarian.totalactions }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="container returnbtn ">
    <div class="row mt-5  " style="text-align:center">
        <div class="col">
            <a href="{% url 'librarian:home-page-view' %}"><button type="submit">Return to home page</button></a>
        </div>
        <div class="col">
            <a href="{% url 'librarian:send-notifications-view' %}"><button type="submit">Send Mail
                    Notifications</button></a>
        </div>
    </div>
</div>


{% endif %} {% endblock %}