finalproject/elibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexview, name='index-view'),
    path('users/', include('users.urls')),
    path('student/', include('student.urls')),
    path('librarian/', include('librarian.urls')),
]

finalproject/librarian/urls.py
from django.urls import path, include

from .views import *

app_name = 'librarian'

urlpatterns = [
    path('home/', homepageview, name='home-page-view'),
    path('home/student-profile/', studentprofileview,
         name='student-profile-view'),
    path('home/issue-book/', issuebookview, name='issue-book-view'),
    path('home/submit-book/', submitbookview, name='submit-book-view'),
    path('send-notifications/', sendnotificationsview,
         name='send-notifications-view'),
]

finalproject/users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    path('', loginview, name='login-view'),
    path('login/', validationview, name='user-validation-view'),
    path('forgot-password/', forgotpasswordview, name='forgot-password-view'),
    path('set-password/', setpasswordview, name='set-password-view'),
    path('set-password/update/', updatepasswordview, name='update-password-view'),
    path('view-profile/', viewprofileview, name='view-profile-view'),
    path('search/', searchresultview, name='search-result-view'),
    path('forgot-password/send-otp/', sendotpview, name="send-otp-view"),
    path('forgot-password/resend-otp/', resendotpview, name="resend-otp-view"),
    path('forgot-password/verify-otp/', verifyotpview, name="verify-otp-view"),
    path('logout', logoutview, name="logout-view"),
]

finalproject/librarian/models.py
from django.db import models

# Create your models here.
from users.models import *


class Librarian(models.Model):
    libid = models.ForeignKey(
        Library_Users, related_name='librarians', on_delete=models.CASCADE)
    title = models.CharField(max_length=4, blank=False, null=False, default="Mr")
    name = models.CharField(max_length=50, blank=False, null=False)
    phone = models.CharField(max_length=10, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    issuedcount = models.IntegerField(default=0, blank=True)
    retrievedcount = models.IntegerField(default=0, blank=True)
    totalactions = models.IntegerField(default=0, blank=True)

class Dashboard(models.Model):
    totalbooks = models.IntegerField(default=0, blank=True)
    booksinside = models.IntegerField(default=0, blank=True)
    issuedbooks = models.IntegerField(default=0, blank=True)
    submittedbooks = models.IntegerField(default=0, blank=True)

finalproject/librarian/forms.py
from django import forms


class studentsearchform(forms.Form):
    searchprofile = forms.CharField(max_length=10, label='Search Here', widget=forms.TextInput(attrs={
        'placeholder': '     Search Profile',
        'class': 'form-bg',
        'id': 'profile',

    }))


class bookactionform(forms.Form):
    rollno = forms.CharField(max_length=10, label='Enter Roll No', widget=forms.TextInput(attrs={
        'placeholder': 'Enter Roll No',
        'id': 'stdid',
        'class': 'input_align',
        'size': '48',
    }))
    bookid = forms.CharField(max_length=5, label='Enter Book ID', widget=forms.TextInput(attrs={
        'placeholder': 'Enter Book ID',
        'id': 'bookid',
        'class': 'input_align',
        'size': '48',
    }))

finalproject/librarian/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse

# Create your views here.
from users.forms import *
from .forms import *

from users.models import *
from student.models import *
from .models import *

import datetime

from users.helper import *
from .mailer import *


def homepageview(request, *args, **kwargs):
    username = request.session['curr_user_id']
    searchform = searchboxform()
    studentprofileform = studentsearchform()
    bookform = bookactionform()
    dashboard = Dashboard.objects.get(id=1)
    transactions = History.objects.all().order_by('-id')[:10]

    if 'issue_book_error' in request.session:
        issue_error = request.session['issue_book_error']
        del request.session['issue_book_error']
    else:
        issue_error = ''

    if 'submit_book_error' in request.session:
        submit_error = request.session['submit_book_error']
        del request.session['submit_book_error']
    else:
        submit_error = ''

    if 'mail_notification' in request.session:
        mail_notification = request.session['mail_notification']
        del request.session['mail_notification']
    else:
        mail_notification = ''

    return render(request, 'librarian/homepage.html', {
        'username': username,
        'searchform': searchform,
        'studentprofileform': studentprofileform,
        'bookactionform': bookform,
        'dashboard': dashboard,
        'transactions': transactions,
        'issue_error': issue_error,
        'submit_error': submit_error,
        'mail_notification': mail_notification,
    })


def studentprofileview(request, *args, **kwargs):
    username = request.session['curr_user_id']
    searchform = searchboxform()
    studentprofileform = studentsearchform()
    bookform = bookactionform()
    dashboard = Dashboard.objects.get(id=1)
    transactions = History.objects.all().order_by('-id')[:10]
    errormsg = ''

    if 'issue_book_error' in request.session:
        issue_error = request.session['issue_book_error']
        request.session['issue_book_error'] = ''
    else:
        issue_error = ''

    if 'submit_book_error' in request.session:
        submit_error = request.session['submit_book_error']
        request.session['submit_book_error'] = ''
    else:
        submit_error = ''

    if request.method == 'GET':
        searchedQuery = True
        if request.GET == {}:
            searchedQuery = False
            return HttpResponseRedirect(reverse('librarian:home-page-view'))
        else:
            studentprofileform = studentsearchform(request.GET)
            if studentprofileform.is_valid():
                searchid = studentprofileform.cleaned_data['searchprofile']
                try:
                    user = Library_Users.objects.get(userid=searchid)
                    studentprofile = Students.objects.get(studid=user)
                except:
                    searchedQuery = False
                    return HttpResponseRedirect(reverse('librarian:home-page-view'))

                activebooks = Issued_Books.objects.filter(studid=user)
                for activebook in activebooks:
                    activebook.amountdue = fine(
                        activebook.duedate, datetime.now().date())
                    activebook.save()

                studimage = f'users/images/{studentprofile.studid}.jpg'

                # student id is verified and profile is retrieved!!
                return render(request, 'librarian/studentprofile.html', {
                    'username': username,
                    'searchform': searchform,
                    'studentprofileform': studentprofileform,
                    'searchedquery': searchedQuery,
                    'activebooks': activebooks,
                    'student': studentprofile,
                    'studimage': studimage,
                    'bookactionform': bookform,
                    'dashboard': dashboard,
                    'transactions': transactions,
                    'issue_error': issue_error,
                    'submit_error': submit_error,
                })
            else:
                searchedQuery = False
                return HttpResponseRedirect(reverse('librarian:home-page-view'))

    return render(request, 'librarian/studentprofile.html', {
        'username': username,
        'searchform': searchform,
        'studentprofileform': studentprofileform,
        'searchedquery': False,
        'errors': errormsg,
        'bookactionform': bookform,
        'dashboard': dashboard,
        'transactions': transactions,
        'issue_error': issue_error,
        'submit_error': submit_error,
    })


def issuebookview(request, *args, **kwargs):
    request.session['issue_book_error'] = ''
    if request.method == 'POST':
        worker = Library_Users.objects.get(
            userid=request.session['curr_user_id'])
        active_librarian = Librarian.objects.get(libid=worker)
        bookform = bookactionform(request.POST)
        if bookform.is_valid():
            studid = bookform.cleaned_data['rollno']
            bookid = bookform.cleaned_data['bookid']
            try:
                student = Library_Users.objects.get(userid=studid)
            except:
                request.session['issue_book_error'] = 'Invalid Student ID'
                return HttpResponseRedirect(reverse('librarian:home-page-view'))
            try:
                book = Books.objects.get(bookid=bookid)
            except:
                request.session['issue_book_error'] = 'Invalid Book ID'
                return HttpResponseRedirect(reverse('librarian:home-page-view'))
            # post validity of roll no of student

            activebooks = Issued_Books.objects.filter(studid=student)

            if len(activebooks) == 3:
                request.session['issue_book_error'] = 'Maximum Books Limit Reached'
                return HttpResponseRedirect(reverse('librarian:home-page-view'))

            bookhad = Issued_Books.objects.filter(studid=student, bookid=book)

            if bookhad:
                request.session['issue_book_error'] = 'Book is already taken by this User'
                return HttpResponseRedirect(reverse('librarian:home-page-view'))

            if book.copies <= 0:
                request.session['issue_book_error'] = 'No copies availble for this Book ID'
                return HttpResponseRedirect(reverse('librarian:home-page-view'))

            book.copies -= 1
            book.save()
            timestamp = datetime.now()
            due = duedate(timestamp.date())
            record = Issued_Books(timestamp=timestamp, studid=student,
                                  libid=worker, bookid=book, bookname=book.bookname, duedate=due)
            record.save()
            record = History(timestamp=timestamp, studid=student, libid=worker, bookid=book,
                             bookname=book.bookname, ttype='Issue', copies=book.copies, amount=0)
            record.save()
            dashboard = Dashboard.objects.get(id=1)
            dashboard.booksinside -= 1
            dashboard.issuedbooks += 1
            dashboard.save()
            active_librarian.issuedcount += 1
            active_librarian.totalactions += 1
            active_librarian.save()
        else:
            request.session['issue_book_error'] = 'Invalid details'
    else:
        request.session['issue_book_error'] = 'Invalid action'
    return HttpResponseRedirect(reverse('librarian:home-page-view'))


def submitbookview(request, *args, **kwargs):
    request.session['submit_book_error'] = ''
    if request.method == 'POST':
        worker = Library_Users.objects.get(
            userid=request.session['curr_user_id'])
        active_librarian = Librarian.objects.get(libid=worker)
        bookform = bookactionform(request.POST)
        if bookform.is_valid():
            studid = bookform.cleaned_data['rollno']
            bookid = bookform.cleaned_data['bookid']
            try:
                student = Library_Users.objects.get(userid=studid)
            except:
                request.session['submit_book_error'] = 'Invalid Student ID'
                return HttpResponseRedirect(reverse('librarian:home-page-view'))
            try:
                book = Books.objects.get(bookid=bookid)
            except:
                request.session['submit_book_error'] = 'Invalid Book ID'
                return HttpResponseRedirect(reverse('librarian:home-page-view'))
            # post validity of roll no of student

            # activebooks = Issued_Books.objects.filter(studid=student)

            bookhad = Issued_Books.objects.filter(studid=student, bookid=book)

            if bookhad:
                booktaken = Issued_Books.objects.get(
                    studid=student, bookid=book)
            else:
                request.session['submit_book_error'] = 'Book is not taken by this User'
                return HttpResponseRedirect(reverse('librarian:home-page-view'))

            finepayable = fine(booktaken.duedate, datetime.now().date())
            if booktaken.amountdue == finepayable:
                if finepayable > 0:
                    request.session['submit_book_error'] = f'Book has {finepayable} Rs. of fine to pay!'
                    return HttpResponseRedirect(reverse('librarian:home-page-view'))
                else:
                    pass
            else:
                if finepayable > 0:
                    booktaken.amountdue = finepayable
                    booktaken.save()
                    request.session['submit_book_error'] = f'Book has {finepayable} Rs. of fine to pay!'
                    return HttpResponseRedirect(reverse('librarian:home-page-view'))

            paymentlist = Payment_View.objects.filter(
                studid=student, bookid=book)

            totalpaidamount = 0
            for payment in paymentlist:
                totalpaidamount += payment.amount

finalproject/librarian/templates/librarian/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block head-part %}
<link rel="stylesheet" href="{% static 'librarian/css/homepage.css' %}">
{% endblock %}

{% block bg-part %}
style="background:transparent url('{% static 'users/images/hologram.png' %}') no-repeat fixed center center / 40% 70%"
{% endblock %}

{% block header-other-half %}
<div class="container">
    <div class="row m-4 p-2 ">
        <div class="col text-align ml-5">
            <a href='{% url "users:view-profile-view" %}'>
                <text class="rollno-color ">{{ username }}</text>
            </a>
        </div>

        <div class="col lout-text-align ">
            <a href="{% url 'users:logout-view' %}">
                <text class="logoutcolor">Logout</text>
            </a>
        </div>
    </div>
</div>
{% endblock %}

{% block body-part %}
<div class="container-fluid ">
    <div class="row m-3 pt-2">
        <div class="col-6 pl-5">
            <form action="{% url 'librarian:student-profile-view' %}" method="GET">
                {{ studentprofileform.searchprofile }}
                <input type="submit" class="search-button" value="">
            </form>
        </div>
        <div class="col-6 pr-5 ">
            <form action="{% url 'users:search-result-view' %}" method="GET">
                {{ searchform.searchbox }}
                <input type="submit" class="search-button" value="">
            </form>
        </div>
    </div>
</div>

<div class="container-fluid ml-5 pl-5">
    <div class="row ">
        <div class="col-8 ">
            <div style="height:500px; overflow-y: scroll; overflow-x: hidden;" class="scrol">
                <div class="row ">
                    <div class="col-12">
                        {% block student-profile %}
                        {% endblock %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-5 mr-5  pr-5 ">
                        <text class="card_txt ">Book Issue</text>
                        <div class="card shadow" style="width:27rem;">
                            <div class="card-body card_b_color border border-5 border-dark" style="text-align:center">
                                <form class="form" action="{% url 'librarian:issue-book-view' %}" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{ bookactionform.rollno }}
                                    </div>

                                    <div class="form-group">
                                        {{ bookactionform.bookid }}
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-sm mb-1">
                                        <h5>Issue</h5>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="ml-5"></div>
                    <div class="col-5 mr-5  pr-5">

                        <text class="card_txt_2 pl-3">Book Retrieval</text>
                        <div class="card shadow " style="width:27rem;">
                            <div class="card-body card_b_color border border-5  border-dark" style="text-align:center">
                                <form class="form " action="{% url 'librarian:submit-book-view' %}" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{ bookactionform.rollno }}
                                    </div>

                                    <div class="form-group">
                                        {{ bookactionform.bookid }}
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-md">
                                        <h5>Submit</h5>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col">
                        {% if issue_error %}
                        <div class="alert alert-danger alert-dismissible fade show card-pos" style="width:fit-content; margin: 0 auto;" role="alert">
                            <strong>{{ issue_error }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        {% if submit_error %}
                        <div class="alert alert-danger alert-dismissible fade show card-pos" style="width:fit-content; margin: 0 auto;" role="alert">
                            <strong>{{ submit_error }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        {% if mail_notification %}
                        <div class="alert alert-success alert-dismissible fade show card-pos" style="width:fit-content; margin: 0 auto;" role="alert">
                            <strong>{{ mail_notification }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="row px-3 mt-4">
                    <text class="trans_txt">Transactions</text>
                    <table class="table table_control">
                        <thead>
                            <tr>
                                <th scope="col">Time Stamp</th>
                                <th scope="col">Librarian ID</th>
                                <th scope="col">Student Roll no</th>
                                <th scope="col">Book ID</th>
                                <th scope="col">Book Name</th>
                                <th scope="col">Copies Available</th>
                                <th scope="col">Type</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for instance in transactions %}
                            <tr>
                                <td scope="col">{{ instance.timestamp }}</td>
                                <td scope="col">{{ instance.libid }}</td>
                                <td scope="col">{{ instance.studid }}</td>
                                <td scope="col">{{ instance.bookid }}</td>
                                <td scope="col">{{ instance.bookname }}</td>
                                <td scope="col">{{ instance.copies }}</td>
                                <td scope="col">{{ instance.ttype }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-4 pl-4 ">
            <div class="container">
                <text class="dash_txt">Dashboard</text>
                <div class="card-deck text-center ">
                    <div class="card dashboardcard">
                        <div class="card-body">
                            <div>
                                <text class="num_txt">{{ dashboard.totalbooks }}</text>
                                <br><text class="num_txt2">Total Books</text>
                            </div>
                            <div class="pt-3 mt-3">
                                <text class=" num_txt">{{ dashboard.booksinside }}</text>
                                <br><text class="num_txt2">Books Inside</text>
                            </div>
                            <div class="pt-3 mt-3">
                                <text class="num_txt"> {{ dashboard.issuedbooks }}</text>
                                <br><text class="num_txt2">Books Issued</text>
                            </div>
                            <div class="pt-3 mt-3">
                                <text class="num_txt">{{ dashboard.submittedbooks }}</text>
                                <br><text class="num_txt2">Books Submitted</text>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

finalproject/librarian/templates/librarian/mailtemp1.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Mail Type 1</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col" style="align-content: center;">
                <h4>Submission is Near</h4>
                <p>
                    Hello {{ student.name }},
                </p>
                <p>
                    Your submission date for {{ book.bookname }} bearing bookid {{ book.bookid }} is coming nearby,
                    i.e {{ book.duedate }}. Please, kindly submit the book as early as possible on or before
                    the deadline, to avoid any unnecessary fines.
                </p>


                <p>With Regards,</p>
                <p>Librarian at GVPCE.</p>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>

</html>

finalproject/librarian/templates/librarian/mailtemp2.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Mail Type 2</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col" style="align-content: center;">
                <h4>Fine to Pay</h4>
                <p>
                    Hello {{ student.name }},
                </p>
                <p>
                    Your submission date for {{ book.bookname }} bearing bookid {{ book.bookid }} has past away
                    on {{ book.duedate }}. Please, kindly pay the fine of Rs.{{ book.amountdue }} and submit the
                    book as of today, to avoid any more unnecessary fines.
                </p>


                <p>With Regards,</p>
                <p>Librarian at GVPCE.</p>
            </div>
        </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>

</html>

finalproject/librarian/templates/librarian/studentprofile.html
{% extends 'librarian/homepage.html' %}
{% load static %}

{% block student-profile %}

<text class="trans_txt">Student Profile</text>
{% if searchedquery %}
<div class="container container_color p-1 mb-3">
    <div class="row ">
        <div class="col-4 ml-5">
            <img src="{% static studimage %}" alt="profile-image" onerror="callfun(this);" width=120 height=110 alt="profile-image" />
        </div>
        <div class="col m-3">
            <table>
                <tbody>
                    <tr>
                        <td class="std_details">
                            Name &emsp;&emsp;&emsp;:
                        </td>
                        <td class="std_details">
                            {{ student.name }}
                        </td>
                    </tr>
                    <tr>
                        <td class="std_details">
                            Roll Number :&emsp;&emsp;
                        </td>
                        <td class="std_details">
                            {{ student.studid }}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row p-1">
        <div class="col">
            <table class="table border border-dark pl-1">
                <thead>
                    <tr>
                        <td>
                            <h6>
                                Book ID
                            </h6>
                        </td>
                        <td>
                            <h6>
                                Issue Date
                            </h6>
                        </td>
                        <td>
                            <h6>
                                Due Date
                            </h6>
                        </td>
                        <td>
                            <h6>
                                Amount Due
                            </h6>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    {% for row in activebooks %}
                    <tr>
                        <td>{{ row.bookid }}</td>
                        <td>{{ row.timestamp }}</td>
                        <td>{{ row.duedate }}</td>
                        <td>{{ row.amountdue }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endif %}
<script>
    function callfun(obj)
    {
        var noimg = "{% static 'users/images/alt.png' %}";
        obj.src=noimg;
    }
</script>
{% endblock %}